services:
  auth_service:
    build:
      context: ./backend/auth_service
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/virtual_closet_db

  closet_service:
    build:
      context: ./backend/closet_service
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/virtual_closet_db

  analytics_service:
    build:
      context: ./backend/analytics_service
    ports:
      - "5003:5003"
    depends_on:
      - db
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/virtual_closet_db

  gateway_service:
    build:
      context: ./backend/gateway_service
    ports:
      - "5005:5005"
    depends_on:
      - auth_service
      - closet_service
      - analytics_service
    environment:
      - FLASK_ENV=production
      - AUTH_SERVICE_URL=http://auth_service:5001
      - CLOSET_SERVICE_URL=http://closet_service:5000
      - ANALYTICS_SERVICE_URL=http://analytics_service:5003

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

  db:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "virtual_closet_db"
